### ISSUE TITLE
App crashes on startup (IOS)

### ISSUE THREAD

**Issue by tsdevelopment** [juicycleff/flutter-unity-view-widget#140] opened 2020-05-09 17:43 UTC
Whenever I start my APP it crashes. I use an empty unity project (one default scene) that runs on my Iphone when I compile directly from unity. It also compiles when I remove the `UnityWidget` and replace it with a `Text` widget.

My main.dart file:

```dart

import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

void main() async => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Test'),
        ),
        body: UnityDemoScreen(),
      ),
    );
  }
}

class UnityDemoScreen extends StatefulWidget {
  UnityDemoScreen({Key key}) : super(key: key);

  @override
  _UnityDemoScreenState createState() => _UnityDemoScreenState();
}

class _UnityDemoScreenState extends State<UnityDemoScreen> {
  static final GlobalKey<ScaffoldState> _scaffoldKey =
      GlobalKey<ScaffoldState>();
  UnityWidgetController _unityWidgetController;

  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: SafeArea(
        bottom: false,
        child: Container(
          child: UnityWidget(
            onUnityViewCreated: onUnityCreated,
          ),
        ),
      ),
    );
  }

  // Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) {
    this._unityWidgetController = controller;
  }
}

```

Error from xcode:

<img width="803" alt="xcode-error" src="https://user-images.githubusercontent.com/4952908/81480917-f41d5200-922c-11ea-84e4-8945d9da72b7.png">

Do you have any Idea whats' wrong here? I use `Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale de-DE)`and as device `Iphone 6S iOS 13.4.1`.

**Comment by paolorotolo** [comment] 2020-05-10 10:15
Yes, it's a possible duplicate of this: https://github.com/flutter/flutter/issues/56452

**Closed** 2020-09-30 15:36 UTC
