### ISSUE TITLE
Flutter to Unity  Communication Steps Unclear

### ISSUE THREAD

**Issue by omarsalem15** [juicycleff/flutter-unity-view-widget#767] opened 2023-02-13 15:35 UTC
can someone tell me the steps to make a game object disappear in the scene when I click on the button made by flutter

**Comment by timbotimbo** [comment] 2023-02-13 15:42
Duplicate of #765

**Closed by timbotimbo** 2023-02-13 15:42 UTC
Labels: duplicate

**Comment by omarsalem15** [comment] 2023-02-13 15:47
> Duplicate of #765


so what are the steps?
