### ISSUE TITLE
 Failed to transform unity-classes.jar to match attributes 

### ISSUE THREAD

**Issue by DenisKen** [juicycleff/flutter-unity-view-widget#780] opened 2023-02-27 13:42 UTC
` 
* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':app:compileDebugKotlin'
   > Could not resolve all files for configuration ':app:debugCompileClasspath'.
      > Failed to transform unity-classes.jar to match attributes {artifactType=android-classes-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
         > Execution failed for JetifyTransform: D:\Documents\Github\mh_projects\flutter-app\android\app\unityLibrary\libs\unity-classes.jar.
            > Transform's input file does not exist: D:\Documents\Github\mh_projects\flutter-app\android\app\unityLibrary\libs\unity-classes.jar. (See https://issuetracker.google.com/issues/158753935)      
`

**Comment by timbotimbo** [comment] 2023-04-18 11:46
I'm closing this in the assumption that this is the same as your #779, caused by following outdated instructions.

You can reopen this if it occurs again with the latest setup from the readme.

**Closed by timbotimbo** 2023-04-18 11:46 UTC
