### ISSUE TITLE
Problems handling Android LifeCycle

### ISSUE THREAD

**Issue by Kingtous** [juicycleff/flutter-unity-view-widget#207] opened 2020-09-16 01:25 UTC
I'm using Flutter 1.20.2 stable.
When I open my flutter unity app, it works fine. But if I switch to my launcher home page and switch back to the app, the unity widget freezes and the screen start shaking. If I do "hot-reload" after that time, it will be fine again.
Anyone has the solution for it? Thanks.

I'had handled the lifecycle by using the codes below, but it's not working.
```dart
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print(state.toString());
    switch (state) {
      case AppLifecycleState.resumed:
        _unityWidgetController?.isReady()?.then((ready) {
          debugPrint("unity resumed");
          // _unityWidgetController?.resume();
        });
        break;
      case AppLifecycleState.inactive:
        // _unityWidgetController?.isReady()?.then((ready) {
        //   debugPrint("unity inactive");
        //   _unityWidgetController?.pause();
        // });
        break;
      case AppLifecycleState.paused:
        _unityWidgetController?.isReady()?.then((ready) {
          debugPrint("unity paused");
          _unityWidgetController?.pause();
        });
        break;
      case AppLifecycleState.detached:
      // UnityWidget的销毁由Widget自己的dispose方法
      //_unityWidgetController?.
        break;
    }

```

**Comment by juicycleff** [comment] 2020-09-16 09:27
@Kingtous we have lifecycle support prebaked in the plugin now. I just have some legal side managed before publishing it

**Comment by juicycleff** [comment] 2020-09-17 13:08
Made a release so please go ahead and test 2.0.0

**Comment by Kingtous** [comment] 2020-09-18 14:45
Got it. I'll try it. Thanks for your reply and make the breaking improvement to this plugin.

**Comment by Kingtous** [comment] 2020-09-19 04:31
when building release package,the error message shows below.

```shell
D8: Program type already present: com.unity3d.player.UnityPlayerActivity                                           
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:                            
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.       
Program type already present: com.unity3d.player.UnityPlayerActivity                                               
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)        
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)             
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)               
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)                        
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)                        
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)                    
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)     
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)     
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)         
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)      
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)                               
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)                               
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)       
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)        
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)                
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)                
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)  
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)                   
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                         
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                         
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)   
        at java.lang.Thread.run(Thread.java:748)                                                                   
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete                         
        at com.android.tools.r8.utils.t.a(:55)                                                                     
        at com.android.tools.r8.D8.run(:11)                                                                        
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)             
        ... 34 more                                                                                                
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.unity3d.player.UnityPlayerActivity
        at com.android.tools.r8.utils.Reporter.a(:21)                                                              
        at com.android.tools.r8.utils.Reporter.a(:7)                                                               
        at com.android.tools.r8.utils.t.a(:36)                                                                     
        ... 36 more                                                                                                
                                                                                                                   
                                                                                                                   
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app:mergeDexRelease'.                                                                  
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:                       
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.  
     Program type already present: com.unity3d.player.UnityPlayerActivity                                          
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 2m 54s

```

**Comment by Kingtous** [comment] 2020-09-19 11:24
> Made a release so please go ahead and test 2.0.0

2.0.0 not working.

**Comment by juicycleff** [comment] 2020-09-21 12:53
@Kingtous this was a duplicate class in the package which has been fixed in 2.0.0+1

**Comment by Kingtous** [comment] 2020-09-27 14:20
I've tested myapp on HUAWEI Honor Play, and it works fine. But it's not working(freezes and the screen start shaking) on XIAOMI MI 8. Maybe it's a bug from MIUI 12 system.

**Comment by hyperms** [comment] 2020-09-28 12:22
### I have a similar problem in release

> D8: Program type already present: com.unity3d.player.GoogleARCoreApi
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.unity3d.player.GoogleARCoreApi
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.t.a(:55)
        at com.android.tools.r8.D8.run(:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
        ... 34 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.unity3d.player.GoogleARCoreApi
        at com.android.tools.r8.utils.Reporter.a(:21)
        at com.android.tools.r8.utils.Reporter.a(:7)
        at com.android.tools.r8.utils.t.a(:36)
        ... 36 more


> FAILURE: Build failed with an exception.

> * What went wrong:

> Execution failed for task ':app:mergeDexRelease'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: com.unity3d.player.GoogleARCoreApi

**Comment by Abdelkareem-dev** [comment] 2020-11-10 11:10
me too, I have the same duplicate classes when building the release version.

**Comment by juicycleff** [comment] 2020-11-19 18:42
@Abdelkareem-dev a fix for the duplicate class issue was because of a bad regex replace when exporting for android, next PR will contain the fix. but you can fix it by looking at your build.gradle file to make sure the player os not imported twice

**Closed** 2020-11-21 20:57 UTC
