### ISSUE TITLE
Could not find method implementation() 

### ISSUE THREAD

**Issue by DenisKen** [juicycleff/flutter-unity-view-widget#774] opened 2023-02-22 12:53 UTC
`
A problem occurred evaluating root project 'android'. Could not find method implementation() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

This line in `build.gradle` got error
![image](https://user-images.githubusercontent.com/15076521/220616946-3dc6661c-7ea5-4300-b317-6c133fd81d50.png)

![image](https://user-images.githubusercontent.com/15076521/220624954-5b8fabca-fe38-4989-8404-4f83c1121bcf.png)
My project is showing red label too.

**Unity (please complete the following information):**
- Android 2021.1.4f

**Smartphone (please complete the following information):**
 Android Asus Rog phone 5

**Comment by timbotimbo** [comment] 2023-02-27 14:23
I don't see this line in either the example project or my personal projects.

It isn't added by the export script, and  it isn't mentioned in the readme either.

You might be using an outdated tutorial or something.

**Comment by timbotimbo** [comment] 2023-04-18 11:47
I'm closing this in the assumption that this is the same as your #779, caused by following outdated instructions.

You can reopen this if it occurs again with the latest setup from the readme.

**Closed by timbotimbo** 2023-04-18 11:47 UTC
Labels: outdated
