### ISSUE TITLE
IMPORTS NEEDED IN (Assets/FlutterUnityIntegration/NativeAPI.cs)

### ISSUE THREAD

**Issue by nic001a** [juicycleff/flutter-unity-view-widget#686] opened 2022-09-02 12:05 UTC
**Describe the bug**

**To Reproduce**
1. Import the fuw in a new unity project 

**Expected behavior**
The fuw shouold be working from the first import without any issues 

**Screenshots**
![Screenshot from 2022-09-02 13-00-03](https://user-images.githubusercontent.com/51291148/188138759-8cebfd01-c311-4035-bded-cf3c8cc3cd7a.png)

**Unity (please complete the following information):**
 - OS: [Pop_OS ]
 - Version 2012.3.61f

**Additional context**
this bug can be fixed by adding the two following lines to **Assets/FlutterUnityIntegration/NativeAPI.cs**
```
using UnityEngine;
unsing System;
```

**Comment by Ahmadre** [comment] 2022-09-04 16:01
Duplicate of: https://github.com/juicycleff/flutter-unity-view-widget/issues/577

**Comment by Ahmadre** [comment] 2022-09-04 16:01
Note: Please use our latest unity package

**Closed by Ahmadre** 2022-09-04 16:01 UTC
