### ISSUE TITLE
Archive or build release in ios fails but in debug is running smoothly

### ISSUE THREAD

**Issue by ruslanou** [juicycleff/flutter-unity-view-widget#218] opened 2020-10-01 12:07 UTC
<img width="267" alt="Screen Shot 2020-10-01 at 7 06 11 PM" src="https://user-images.githubusercontent.com/45680974/94807097-544da400-0419-11eb-8b3b-16693bd17bfb.png">

I'm gonna provide the screenshot of the error state. Please resolve this problem. It's really urgent :)

**Comment by giovannowarli** [comment] 2020-10-01 12:33
Hey! I'm experiencing the same issue! Anyone can help?

**Comment by ToddBrawn** [comment] 2020-10-10 17:10
I am also seeing this issue. I have tried a couple of solutions mentioned, but none seem to resolve for me.

**Comment by MugOfPaul** [comment] 2020-10-22 23:29
I believe this is a dupe of #83 and I think I have a fix...

These changes must be applied to **both the Runner and Pods Projects**: 
- In Project "Info" tab, change iOS Deployment Target from `8.0` to `12.0`
- In Project "Build Settings" tab, change Architectures from `Standard Architectures` to `arm64`

![image](https://user-images.githubusercontent.com/481248/96940037-8172fc80-1483-11eb-809c-11c37943c76f.png)
![image](https://user-images.githubusercontent.com/481248/96940058-90f24580-1483-11eb-8b17-2fbbc0d13c0c.png)
![image](https://user-images.githubusercontent.com/481248/96940088-a0718e80-1483-11eb-97e0-186f89735c33.png)
![image](https://user-images.githubusercontent.com/481248/96940106-ab2c2380-1483-11eb-8ff9-30779bec216b.png)

There may be a slicker way to deal with the architecture but these build times are too brutal for me to keep tinkering with it further. arm64 should be safe - especially if you're building an AR app which is going to require fairly new hardware. 

I am not ready to submit a build with these changes. If you pass submission, let me know!

**Comment by juicycleff** [comment] 2020-11-21 21:17
@MugOfPaul did you manage to solve this problem

**Comment by jbogp** [comment] 2020-12-08 19:28
I've tried everything described here but still can't get a profiling build to complete :( Still stuck with the UnityFramework.h not found, when the app works perfectly in debug mode. I'm on Xcode 12 and iOS 14

**Comment by jbogp** [comment] 2020-12-08 21:12
Oh actually, I still get the error when running `Profile main.dart` but I was able to build install and run the app after trying `flutter run --release` from the console 🎉

**Comment by albemala** [comment] 2021-03-07 10:06
Make sure your Unity XCode project configurations match those of your app XCode project.

e.g., if you have a `Debug dev` configuration for your app, make sure to have a configuration with **exactly** the same name in the Unity XCode project as well. Like in these images:

![Screenshot 2021-03-05 at 16 46 24](https://user-images.githubusercontent.com/2332860/110236179-481bc480-7f2c-11eb-8b94-82f92f6d1410.png)

![Screenshot 2021-03-05 at 16 45 39](https://user-images.githubusercontent.com/2332860/110236182-4b16b500-7f2c-11eb-9770-b24da41058ba.png)

@jbogp I suspect you can't run your app in Profile mode because, by default, the Unity XCode project doesn't have a `Profile` configuration.

You can duplicate an existing configuration using the `+` button at the bottom of the configurations list.

**Comment by tomalabaster** [comment] 2021-03-31 09:12
> Make sure your Unity XCode project configurations match those of your app XCode project.
> 
> e.g., if you have a `Debug dev` configuration for your app, make sure to have a configuration with **exactly** the same name in the Unity XCode project as well. Like in these images:
> 
> ![Screenshot 2021-03-05 at 16 46 24](https://user-images.githubusercontent.com/2332860/110236179-481bc480-7f2c-11eb-8b94-82f92f6d1410.png)
> 
> ![Screenshot 2021-03-05 at 16 45 39](https://user-images.githubusercontent.com/2332860/110236182-4b16b500-7f2c-11eb-9770-b24da41058ba.png)
> 
> @jbogp I suspect you can't run your app in Profile mode because, by default, the Unity XCode project doesn't have a `Profile` configuration.
> 
> You can duplicate an existing configuration using the `+` button at the bottom of the configurations list.

This was what did it for me! I had the same issue as the original comment when running in profile mode.

On the `Unity-iPhone` project in Xcode, I made a copy of the `ReleaseForProfiling` configuration and renamed it `Profile`, then I was able to run `flutter run --profile` successfully.

**Comment by jamesncl** [comment] 2022-06-07 17:13
See [my comment in this duplicate issue](https://github.com/juicycleff/flutter-unity-view-widget/issues/83#issuecomment-1148945351)

**Comment by dawiddszewczyk** [comment] 2022-07-16 17:32
@jamesncl link resolved this problem. In this link you have also my solution.

**Closed by dawiddszewczyk** 2022-07-16 17:32 UTC
