### ISSUE TITLE
Unresolved reference: MultiWindowSupport

### ISSUE THREAD

**Issue by Surya-Flutter** [juicycleff/flutter-unity-view-widget#531] opened 2022-02-04 12:22 UTC
Hi Team, I got this error when i integrated into my project . Build failed .

e: C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_unity_widget-4.2.4\android\src\main\kotlin\com\xraph\plugin\flutter_unity_widget\FlutterUnityWidgetController.kt: (14, 27): Unresolved reference: MultiWindowSupport

**Comment by juicycleff** [comment] 2022-02-04 20:15
On it

**Comment by cc-setwo** [comment] 2022-02-04 21:24
Hello,

Looks like the problem is in the file unity-classes.jar. For some reason when I build Android on Windows PC this file doesn't contain MultiWindowSupport class.
But when I try to build under mac os everything is just fine. 
For now I just suggest to replace the unity-classes.jar file with the file that has been assembled on mac os.
The file is attached.

Regards.

[unity-classes.zip](https://github.com/juicycleff/flutter-unity-view-widget/files/8006308/unity-classes.zip)

**Comment by juicycleff** [comment] 2022-02-04 21:28
Thank @cc-setwo I think it might have to do with the unity version also, could you confirm you have same versions on both platforms?

**Comment by cc-setwo** [comment] 2022-02-04 21:36
@juicycleff 
Not exactly the same, but I have tried different version on Windows: 2018.4.31, 2019.4.20, 2020.3.14f1, and as I remember the result unfortunately is the same.
On mac os the version 2019.4.35f1 gave me the desired result after first try.

So every time I build Android from Windows I just replace the unity-classes.jar file. For now it works for me.

**Comment by juicycleff** [comment] 2022-02-04 22:04
Will just take out the multi-window support for now and make it optional

**Comment by sevantasci** [comment] 2022-02-05 19:13
#521 @juicycleff  can you also check this issue please ? :) it is also another bug depends to unity-classes.jar

**Comment by juicycleff** [comment] 2022-02-05 19:29
Fix coming in a few minutes

**Comment by juicycleff** [comment] 2022-02-06 01:02
@sevantasci please confirm this issue was fixed in the latest release

**Comment by juicycleff** [comment] 2022-02-06 01:03
Removed multiwindow

**Closed by juicycleff** 2022-02-06 01:03 UTC
Labels: bug

**Comment by Surya-Flutter** [comment] 2022-02-06 09:29
Hi @juicycleff , May I know the use of multi window ?

**Comment by juicycleff** [comment] 2022-02-06 09:55
> Hi @juicycleff , May I know the use of multi window ?

Just allows unity still run while app is in multi window mode

**Comment by droncaglio** [comment] 2022-03-15 15:37
> Hello,
> 
> Looks like the problem is in the file unity-classes.jar. For some reason when I build Android on Windows PC this file doesn't contain MultiWindowSupport class. But when I try to build under mac os everything is just fine. For now I just suggest to replace the unity-classes.jar file with the file that has been assembled on mac os. The file is attached.
> 
> @juicycleff fyi
> 
> Regards.
> 
> [unity-classes.zip](https://github.com/juicycleff/flutter-unity-view-widget/files/8006308/unity-classes.zip)

Thanks @cc-setwo I download your file and now my Android project works fine. I think the problem is related to Android SDK 31 because I have to identical projects, but only on the compile version SDK 31 I am facing this issue. On the SDK 29 its working fine. But I can't use 29 because of a camera plugin that I wan't to use and it needs the 31 :/

**Comment by sevantasci** [comment] 2022-03-16 07:27
Can you guys test it with release build, after changing unity-classes.jar. OnUnityMessage didn't work after i build on release.
